"""`lab boottrace`: record every step of a boot and show it as a trace.

The guest is booted with the kernel's initcall tracepoints enabled
(trace_event=initcall:*), then a job collects the ftrace buffer, dmesg and systemd unit
timestamps. Combined with host-side timing (QEMU start vs. arrival of console lines) this
becomes one trace:

    boot <build>
    ├─ pre-kernel        QEMU start, firmware, kernel load + decompression (host-measured)
    ├─ kernel
    │  ├─ start_kernel   arch/mm/sched/irq/timer setup (+ console initcalls)
    │  ├─ early initcalls (pre-SMP)
    │  ├─ SMP bring-up + driver core
    │  ├─ initcalls: pure … late   → one span per initcall (µs exact)
    │  └─ mount root, free init memory, exec /sbin/init
    └─ userspace         one span per systemd unit (activating → active)

Traces go to Tempo (OTLP/HTTP), summary metrics to VictoriaMetrics, everything also to
runs/<id>/ (result.json is `lab compare`-compatible: kernel/userspace/pre-kernel times).
"""

import json
import os
import re
import secrets
import subprocess
import time
import urllib.error
import urllib.parse
from concurrent.futures import ThreadPoolExecutor

from . import common, observe
from .common import RUNS, LabError, info, table, warn
from .common import output
from .kernel import build_dir, build_meta, default_build, tree_path
from .vm import DEFAULT_CPUS, DEFAULT_MEM, run_job

TEMPO_URL = "http://127.0.0.1:3200"
CODE_LINKS_URL = "http://127.0.0.1:3001"   # monitoring/code-links: http -> vscode://file/...
OTLP_URL = "http://127.0.0.1:4318/v1/traces"
TRACE_ARGS = "trace_event=initcall:* trace_buf_size=16M"
LEVELS = ["console", "early", "pure", "core", "postcore", "arch", "subsys", "fs",
          "rootfs", "device", "late"]

COLLECT_JOB = """#!/bin/sh
# Generated by `lab boottrace`: dump boot timing data to the 9p share.
cd /mnt/lab
uname -r > kernel_release
cat /proc/cmdline > cmdline
cat /sys/kernel/tracing/trace > trace.txt
dmesg > dmesg.txt
systemd-analyze time > sa_time.txt 2>&1
systemd-analyze critical-chain --no-pager > sa_chain.txt 2>&1
systemctl show --all --type=service,mount,socket,target,swap,path,timer,device \\
    -p Id,InactiveExitTimestampMonotonic,ActiveEnterTimestampMonotonic > units.txt
"""

# Kernel log lines worth marking on the timeline (name, regex).
MILESTONES = [
    ("kernel starts (Linux version)", r"Linux version"),
    ("command line parsed", r"Command line:"),
    ("BIOS memory map", r"BIOS-provided physical RAM map"),
    ("ACPI tables", r"ACPI: RSDP"),
    ("CPU topology / per-CPU areas", r"setup_percpu:"),
    ("IRQs (NR_IRQS)", r"NR_IRQS:"),
    ("clocksource: tsc-early", r"clocksource: tsc-early"),
    ("delay loop calibrated", r"(Calibrating delay|lpj=)"),
    ("memory: buddy allocator up", r"Memory: \d+K/"),
    ("pid_max", r"pid_max:"),
    ("bringing up secondary CPUs", r"smp: Bringing up secondary CPUs"),
    ("all CPUs online", r"smpboot: Total of"),
    ("devtmpfs initialized", r"devtmpfs: initialized"),
    ("async device probes done (md autodetect starts)", r"md: Waiting for all devices"),
    ("PCI host bridge", r"PCI host bridge to bus"),
    ("virtio block device", r"virtio_blk .*\[vda\]"),
    ("serial console enabled", r"printk: (legacy )?console \[ttyS0\] enabled"),
    ("root fs mounted", r"VFS: Mounted root|EXT4-fs \(vda\): mounted"),
    ("init memory freed", r"Freeing unused kernel image \(initmem\)"),
    ("exec /sbin/init", r"Run /sbin/init"),
    ("systemd starts", r"systemd\[1\]: systemd \d"),
]

TS_RE = re.compile(r"^\[\s*(\d+\.\d+)\]")
TRACE_RE = re.compile(r"\s(\d+\.\d+): (initcall_level|initcall_start|initcall_finish): (.*)$")


# --------------------------------------------------------------------------- parsing

def _fn(raw):
    return raw.split("+", 1)[0]


def parse_trace(text):
    """-> (levels [(name, start)], initcalls [{fn, level, start, end, ret}]) in seconds."""
    levels, calls, open_calls = [], [], {}
    for line in text.splitlines():
        m = TRACE_RE.search(line)
        if not m:
            continue
        ts, ev, rest = float(m.group(1)), m.group(2), m.group(3)
        kv = dict(p.split("=", 1) for p in rest.split() if "=" in p)
        if ev == "initcall_level":
            levels.append((kv.get("level", "?"), ts))
        elif ev == "initcall_start":
            open_calls[kv["func"]] = (ts, levels[-1][0] if levels else "?")
        elif ev == "initcall_finish" and kv.get("func") in open_calls:
            start, level = open_calls.pop(kv["func"])
            size = kv["func"].rsplit("/", 1)[-1]
            calls.append({"fn": _fn(kv["func"]), "level": level, "start": start, "end": ts,
                          "ret": int(kv.get("ret", 0)),
                          "size": int(size, 16) if size.startswith("0x") else 0})
    return levels, calls


def parse_milestones(dmesg):
    out = []
    for name, pat in MILESTONES:
        rx = re.compile(pat)
        for line in dmesg.splitlines():
            m = TS_RE.match(line)
            if m and rx.search(line):
                out.append((name, float(m.group(1)), line[m.end():].strip()[:200]))
                break
    return sorted(out, key=lambda x: x[1])


def parse_units(text):
    """systemctl show blocks -> [{unit, start, end}] in seconds since boot."""
    units = []
    for block in text.strip().split("\n\n"):
        kv = dict(l.split("=", 1) for l in block.splitlines() if "=" in l)
        try:
            start = int(kv.get("InactiveExitTimestampMonotonic", 0))
            end = int(kv.get("ActiveEnterTimestampMonotonic", 0))
        except ValueError:
            continue
        if start and end and end >= start:
            units.append({"unit": kv.get("Id", "?"), "start": start / 1e6, "end": end / 1e6})
    return sorted(units, key=lambda u: u["start"])


def parse_sa_time(text):
    """'Startup finished in 652ms (kernel) + 1.168s (userspace) = …' -> {kernel, userspace}."""
    def secs(tok):
        total = 0.0
        for num, unit in re.findall(r"([\d.]+)(min|ms|us|s)\b", tok):
            total += float(num) * {"min": 60, "s": 1, "ms": 1e-3, "us": 1e-6}[unit]
        return total
    out = {}
    for part in ("kernel", "userspace"):
        m = re.search(r"([\d.a-z ]+?) \(" + part + r"\)", text)
        if m:
            out[part] = secs(m.group(1))
    return out


# --------------------------------------------------------------------------- model

class Span:
    def __init__(self, name, start, end, service, parent=None, attrs=None, events=None,
                 code=None):
        self.id = secrets.token_hex(8)
        self.code = code            # (function, symbol size or 0) to link to its source
        self.name, self.start, self.end, self.service = name, start, max(end, start), service
        self.parent, self.attrs, self.events = parent, attrs or {}, events or []


def build_spans(d):
    """Turn parsed boot data (seconds since kernel t=0) into a span tree."""
    levels, calls, units, miles = d["levels"], d["initcalls"], d["units"], d["milestones"]
    kernel_end = next((t for n, t, _ in miles if n == "exec /sbin/init"), None) \
        or (calls[-1]["end"] if calls else d["sa"].get("kernel", 0))
    user_end = max([u["end"] for u in units] + [kernel_end + d["sa"].get("userspace", 0)])
    pre = d["prekernel"]

    root = Span(f"boot {d['build']}", -pre if pre else 0, user_end, "lab",
                attrs={"build": d["build"], "kernel.release": d["release"], "run": d["run"],
                       "cmdline": d["cmdline"]})
    spans = [root]
    if pre:
        spans.append(Span("pre-kernel: QEMU, firmware, load + decompress", -pre, 0, "firmware",
                          root.id, {"note": "host-measured: QEMU start to kernel t=0 (approx.)"}))
    kernel = Span("kernel", 0, kernel_end, "kernel", root.id,
                  attrs={"initcalls": len(calls)},
                  events=[(t, n, line) for n, t, line in miles])
    spans.append(kernel)

    # A level runs from its initcall_level event to the end of its last initcall.
    bounds = []
    for name, start in levels:
        in_level = [c for c in calls if c["level"] == name]
        bounds.append((name, start, max([start] + [c["end"] for c in in_level])))
    by_name = {n: (s, e) for n, s, e in bounds}

    def phase(name, start, end, attrs=None):
        if start is not None and end is not None and end >= start:
            s = Span(name, start, end, "kernel", kernel.id, attrs)
            spans.append(s)
            return s
        return None

    early = by_name.get("early")
    pure = by_name.get("pure")
    last = bounds[-1] if bounds else None
    phase("start_kernel: arch, mm, sched, irq, timers", 0, early[0] if early else None,
          {"see": "init/main.c:start_kernel()"})
    if early and pure:
        phase("SMP bring-up + driver core (smp_init, driver_init)", early[1], pure[0],
              {"see": "init/main.c:kernel_init_freeable()"})
    if last:
        tail = phase("after initcalls: devices, root fs, exec /sbin/init", last[2], kernel_end,
                     {"see": "init/main.c:kernel_init(), init/do_mounts.c:prepare_namespace()"})
        mark = {n: t for n, t, _ in miles}
        probed = mark.get("async device probes done (md autodetect starts)")
        mounted = mark.get("root fs mounted")
        cuts = [("wait for async device probes (wait_for_device_probe)", last[2], probed),
                ("mount root filesystem", probed or last[2], mounted),
                ("free init memory, mark rodata RO, exec init", mounted, kernel_end)]
        for name, a, b in cuts:
            if tail and a is not None and b is not None and b >= a:
                spans.append(Span(name, a, b, "kernel", tail.id))

    level_spans = {}
    for name, start, end in bounds:
        idx = LEVELS.index(name) if name in LEVELS else 99
        n = sum(1 for c in calls if c["level"] == name)
        level_spans[name] = phase(f"initcalls: {name}", start, end,
                                  {"level": name, "order": idx, "initcalls": n})
    for c in calls:
        parent = level_spans.get(c["level"]) or kernel
        spans.append(Span(c["fn"], c["start"], c["end"], "kernel", parent.id,
                          {"level": c["level"], "ret": c["ret"],
                           "duration_us": round((c["end"] - c["start"]) * 1e6)},
                          code=(c["fn"], c.get("size", 0))))

    user = Span("userspace (systemd)", kernel_end, user_end, "systemd", root.id,
                {"units": len(units)})
    spans.append(user)
    for u in units:
        spans.append(Span(u["unit"], u["start"], u["end"], "systemd", user.id,
                          {"duration_ms": round((u["end"] - u["start"]) * 1e3, 3)}))
    for sp in spans:
        if sp.code is None:
            fn = PHASE_CODE.get(sp.name) or ("do_initcall_level" if sp.name.startswith("initcalls:")
                                             else None)
            sp.code = (fn, 0) if fn else None
        if sp.service == "systemd" and sp.parent == user.id:
            sp.attrs["link.docs"] = unit_docs(sp.name)
    return spans, {"prekernel": pre, "kernel": kernel_end, "userspace": user_end - kernel_end,
                   "total": user_end + (pre or 0)}


# --------------------------------------------------------------------------- source links

# Phase span -> the function that implements it (see init/main.c).
PHASE_CODE = {
    "pre-kernel: QEMU, firmware, load + decompress": "extract_kernel",
    "kernel": "start_kernel",
    "start_kernel: arch, mm, sched, irq, timers": "start_kernel",
    "initcalls: console": "console_init",
    "initcalls: early": "do_pre_smp_initcalls",
    "SMP bring-up + driver core (smp_init, driver_init)": "kernel_init_freeable",
    "after initcalls: devices, root fs, exec /sbin/init": "kernel_init",
    "wait for async device probes (wait_for_device_probe)": "wait_for_device_probe",
    "mount root filesystem": "prepare_namespace",
    "free init memory, mark rodata RO, exec init": "free_initmem",
}


def unit_docs(unit):
    """systemd man page for a unit (systemd-* units have their own page)."""
    base = "https://www.freedesktop.org/software/systemd/man/latest"
    if unit.startswith("systemd-"):
        return f"{base}/{unit}.html"
    kind = unit.rsplit(".", 1)[-1]
    return f"{base}/systemd.special.html" if kind == "target" else f"{base}/systemd.{kind}.html"


class SourceIndex:
    """function -> (absolute path, line) for one build, via vmlinux DWARF (nm + addr2line),
    falling back to `git grep` for functions without a symbol (inlined static helpers).
    Results are cached in builds/<b>/lab-sources.json, keyed by the vmlinux identity."""

    def __init__(self, build):
        meta = build_meta(build)
        self.vmlinux = build_dir(build) / "vmlinux"
        self.cache_file = build_dir(build) / "lab-sources.json"
        self.tree = tree_path(meta["tree"]) if meta.get("tree") else None
        base = output(["git", "-C", self.tree, "describe", "--tags", "--abbrev=0"]) if self.tree else ""
        self.tag = base if re.fullmatch(r"v\d+\.\d+(\.\d+)?(-rc\d+)?", base) else None
        st = self.vmlinux.stat() if self.vmlinux.exists() else None
        self.key = f"{st.st_mtime_ns}-{st.st_size}" if st else ""
        self.map = {}
        try:
            cached = json.loads(self.cache_file.read_text())
            if cached.get("vmlinux") == self.key:
                self.map = cached["functions"]
        except (OSError, ValueError, KeyError):
            pass

    def resolve(self, wanted):
        """wanted: {(function, size)}; fills self.map for the ones not cached yet."""
        todo = {(f, sz) for f, sz in wanted if f and f"{f}/{sz}" not in self.map}
        if not todo or not self.key:
            return
        syms = {}
        names = {f for f, _ in todo}
        nm = subprocess.run(["nm", "-S", "--defined-only", self.vmlinux],
                            capture_output=True, text=True).stdout
        for line in nm.splitlines():
            parts = line.split()
            if len(parts) == 4 and parts[3] in names and parts[2] in "tT":
                syms.setdefault(parts[3], []).append((parts[0], int(parts[1], 16)))
        addr_of = {}
        for f, sz in todo:
            cands = syms.get(f)
            if cands:
                # Duplicate static names: the trace's size (padded) is >= the symbol size.
                fit = [c for c in cands if not sz or c[1] <= sz]
                addr_of[(f, sz)] = max(fit or cands, key=lambda c: c[1])[0]
        if addr_of:
            # addr2line costs ~25 ms/address on compressed DWARF; contiguous address ranges in
            # parallel processes cut a cold lookup of ~750 initcalls from ~20 s to ~5 s.
            keys = sorted(addr_of, key=addr_of.get)
            n = max(1, min(12, os.cpu_count() or 1, len(keys) // 20))
            chunks = [keys[i * len(keys) // n:(i + 1) * len(keys) // n] for i in range(n)]
            with ThreadPoolExecutor(n) as ex:
                outs = ex.map(lambda c: subprocess.run(
                    ["addr2line", "-e", self.vmlinux, *[addr_of[k] for k in c]],
                    capture_output=True, text=True).stdout.splitlines(), chunks)
                pairs = [p for c, o in zip(chunks, outs) for p in zip(c, o)]
            for k, line in pairs:
                path, _, ln = line.split(" ")[0].rpartition(":")
                if path and path != "??" and ln.isdigit() and ln != "0":
                    self.map[f"{k[0]}/{k[1]}"] = [path, int(ln)]
        for f, sz in todo:
            if f"{f}/{sz}" not in self.map and self.tree:
                hit = self._grep(f)
                if hit:
                    self.map[f"{f}/{sz}"] = hit
        try:
            self.cache_file.write_text(json.dumps({"vmlinux": self.key, "functions": self.map}))
        except OSError:
            pass

    def _grep(self, fn):
        out = output(["git", "-C", self.tree, "grep", "-n", "-E", rf"^[A-Za-z_].*[ *]{fn}\(",
                      "--", "*.c"])
        for line in out.splitlines():
            path, ln, text = line.split(":", 2)
            if text.rstrip().endswith(";") or (path.startswith("arch/") and
                                               not path.startswith("arch/x86/")):
                continue
            return [str(self.tree / path), int(ln)]
        return None

    def attrs(self, fn, size=0):
        hit = self.map.get(f"{fn}/{size}")
        if not hit:
            return {}
        path, line = hit
        a = {"code.function": fn, "code.lineno": line,
             "link.vscode": f"{CODE_LINKS_URL}/code?"
                            + urllib.parse.urlencode({"path": path, "line": line}, safe="/")}
        rel = None
        if self.tree and path.startswith(str(self.tree) + "/"):
            rel = path[len(str(self.tree)) + 1:]
        a["code.filepath"] = rel or path
        if rel and self.tag:
            a["link.elixir"] = f"https://elixir.bootlin.com/linux/{self.tag}/source/{rel}#L{line}"
        return a


def attach_sources(spans, build):
    """Add code.* attributes and clickable source links to every span that has code."""
    idx = SourceIndex(build)
    idx.resolve({sp.code for sp in spans if sp.code})
    linked = 0
    for sp in spans:
        if sp.code:
            a = idx.attrs(*sp.code)
            sp.attrs.update(a)
            linked += bool(a)
    return linked


# --------------------------------------------------------------------------- export

def _attr(k, v):
    if isinstance(v, bool):
        val = {"boolValue": v}
    elif isinstance(v, int):
        val = {"intValue": str(v)}
    elif isinstance(v, float):
        val = {"doubleValue": v}
    else:
        val = {"stringValue": str(v)}
    return {"key": k, "value": val}


def otlp(spans, trace_id, t0_ns):
    """OTLP/JSON payload; span times are seconds relative to kernel t=0."""
    ns = lambda t: str(t0_ns + int(round(t * 1e9)))
    by_service = {}
    for s in spans:
        span = {"traceId": trace_id, "spanId": s.id, "name": s.name, "kind": 1,
                "startTimeUnixNano": ns(s.start), "endTimeUnixNano": ns(s.end),
                "attributes": [_attr(k, v) for k, v in s.attrs.items()]}
        if s.parent:
            span["parentSpanId"] = s.parent
        if s.events:
            span["events"] = [{"timeUnixNano": ns(t), "name": n,
                               "attributes": [_attr("log", line)]} for t, n, line in s.events]
        by_service.setdefault(s.service, []).append(span)
    return {"resourceSpans": [
        {"resource": {"attributes": [_attr("service.name", svc)]},
         "scopeSpans": [{"scope": {"name": "klab.boottrace"}, "spans": sp}]}
        for svc, sp in by_service.items()]}


def push_metrics(d, phases, trace_id):
    ts = int(time.time() * 1000)
    L = observe._labels
    base = {"run": d["run"], "build": d["build"]}
    lines = [f'lab_boot_info{L({**base, "kernel": d["release"], "trace_id": trace_id})} 1 {ts}']
    for k, v in phases.items():
        if v:
            lines.append(f'lab_boot_seconds{L({**base, "phase": k})} {v} {ts}')
    for name, start, end, n in d["level_summary"]:
        idx = LEVELS.index(name) if name in LEVELS else 99
        lines.append(f'lab_boot_level_seconds{L({**base, "level": f"{idx:02d} {name}"})} '
                     f'{end - start} {ts}')
    for c in d["initcalls"]:
        lab = {**base, "fn": c["fn"], "level": c["level"]}
        lines.append(f'lab_boot_initcall_seconds{L(lab)} {c["end"] - c["start"]} {ts}')
    for u in d["units"]:
        lines.append(f'lab_boot_unit_seconds{L({**base, "unit": u["unit"]})} '
                     f'{u["end"] - u["start"]} {ts}')
    observe.push(lines)


def tempo_available(wait=60):
    """True once Tempo is ready. A freshly (re)started Tempo answers but reports not-ready
    for ~15 s, so wait for it instead of silently skipping the trace."""
    deadline = time.monotonic() + wait
    announced = False
    while True:
        try:
            observe._request("GET", f"{TEMPO_URL}/ready", timeout=2)
            return True
        except urllib.error.HTTPError:        # up, still starting (503)
            if not announced:
                info("waiting for Tempo to become ready ...")
                announced = True
        except (OSError, urllib.error.URLError):
            return False                      # not running at all
        if time.monotonic() > deadline:
            return False
        time.sleep(1)


def tempo_has(trace_id):
    """Tempo returns 200 with an empty body for unknown IDs, so check the content."""
    try:
        body = observe._request("GET", f"{TEMPO_URL}/api/v2/traces/{trace_id}", timeout=10)
    except (OSError, urllib.error.URLError, ValueError):
        return False
    trace = body.get("trace", body) if isinstance(body, dict) else {}
    return bool(trace.get("resourceSpans") or trace.get("batches"))


def send_trace(payload):
    try:
        observe._request("POST", OTLP_URL, body=payload, timeout=30)
        return True
    except (OSError, urllib.error.URLError) as e:
        warn(f"sending trace to Tempo failed ({e})")
        return False


def resend(quiet=False):
    """Re-upload saved boot traces (runs/*/boot*/trace.otlp.json) that Tempo is missing,
    e.g. after a Tempo restart lost its newest block or a trace was skipped."""
    if not tempo_available():
        raise LabError("Tempo is not running (make observe)")
    sent = checked = 0
    for f in sorted(RUNS.glob("*/boot*/trace.otlp.json")):
        try:
            trace_id = json.loads((f.parent / "boot.json").read_text())["trace_id"]
        except (OSError, ValueError, KeyError):
            continue
        checked += 1
        if not tempo_has(trace_id) and send_trace(json.loads(f.read_text())):
            sent += 1
            if not quiet:
                info(f"re-sent {f.parent.parent.name}/{f.parent.name}")
    if sent or not quiet:
        info(f"boot traces: {checked} saved, {sent} re-sent to Tempo")
    return sent


# --------------------------------------------------------------------------- command

def boottrace(build=None, boots=1, cpus=DEFAULT_CPUS, mem=DEFAULT_MEM, pin=None, append="",
              label=None, timeout=300, no_telemetry=False, top=15):
    build = default_build(build)
    meta = build_meta(build)
    run_id = time.strftime("%Y%m%d-%H%M%S") + f"-{build}-boottrace" + (f"-{label}" if label else "")
    rundir = RUNS / run_id
    export = observe.wanted(no_telemetry)
    tempo = export and tempo_available()
    if export and not tempo:
        warn("Tempo is not up: metrics only. The trace is saved; upload it later with "
             "`lab boottrace --resend` (make observe does this automatically)")
    info(f"boottrace {run_id}: {boots} boot(s) with {TRACE_ARGS}")
    vm_kw = {"cpus": cpus, "mem": mem, "pin": pin, "append": f"{TRACE_ARGS} {append}".strip()}
    if common.DRY:
        run_job(build, rundir / "boot0", None, timeout, **vm_kw)
        return None
    rundir.mkdir(parents=True)

    values = {"prekernel": [], "kernel": [], "userspace": [], "total": []}
    last = None
    for n in range(boots):
        work = rundir / f"boot{n}"
        work.mkdir()
        (work / "job.sh").write_text(COLLECT_JOB)
        arrivals = []
        start_wall = time.time()
        run_job(build, work, rundir / f"console{n}.log", timeout,
                on_line=lambda l: arrivals.append((time.time(), l)), **vm_kw)
        if not (work / "trace.txt").exists():
            raise LabError(f"guest did not produce boot data; see {rundir}/console{n}.log")

        # Kernel t=0 on the wall clock: each console line "[ts] ..." arrived at or after
        # t0 + ts, so the smallest (arrival - ts) is the best estimate.
        t0 = min((a - float(m.group(1)) for a, l in arrivals
                  if (m := TS_RE.match(l.strip()))), default=None)
        levels, calls = parse_trace((work / "trace.txt").read_text(errors="replace"))
        d = {
            "run": run_id if boots == 1 else f"{run_id}-b{n}", "build": build,
            "release": (work / "kernel_release").read_text().strip(),
            "cmdline": (work / "cmdline").read_text().strip(),
            "levels": levels, "initcalls": calls,
            "milestones": parse_milestones((work / "dmesg.txt").read_text(errors="replace")),
            "units": parse_units((work / "units.txt").read_text(errors="replace")),
            "sa": parse_sa_time((work / "sa_time.txt").read_text(errors="replace")),
            "prekernel": (t0 - start_wall) if t0 else None,
        }
        spans, phases = build_spans(d)
        linked = attach_sources(spans, build)
        d["level_summary"] = [(s.attrs["level"], s.start, s.end, s.attrs["initcalls"])
                              for s in spans if "order" in s.attrs]
        trace_id = secrets.token_hex(16)
        t0_ns = int((t0 or start_wall) * 1e9)
        payload = otlp(spans, trace_id, t0_ns)
        (work / "trace.otlp.json").write_text(json.dumps(payload))
        (work / "boot.json").write_text(json.dumps(
            {**d, "phases": phases, "trace_id": trace_id}, indent=1, default=str))
        if tempo:
            send_trace(payload)
        if export:
            push_metrics(d, phases, trace_id)
        for k in values:
            if phases.get(k):
                values[k].append(phases[k])
        last = (d, phases, trace_id)
        info(f"boot {n + 1}/{boots}: kernel {phases['kernel'] * 1e3:.0f} ms, "
             f"userspace {phases['userspace'] * 1e3:.0f} ms, {len(calls)} initcalls, "
             f"{linked} spans linked to source")

    result = {
        "id": run_id, "label": label, "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "build": build, "tree": meta.get("tree"), "profile": meta.get("profile"),
        "commit": meta.get("commit"), "describe": meta.get("describe"),
        "config_hash": meta.get("config_hash"),
        "guest": {"kernel_release": last[0]["release"]},
        "vm": {"cpus": cpus, "mem": mem, "pin": pin, "append": vm_kw["append"]},
        "params": {"repeat": 1, "warmup": 0, "boots": boots},
        "telemetry": False,
        "results": {"boottrace": {k: {"unit": "s", "better": "lower", "values": v}
                                  for k, v in values.items() if v}},
    }
    (rundir / "result.json").write_text(json.dumps(result, indent=2) + "\n")
    report(*last, top=top)
    info(f"saved runs/{run_id}/ (boot*/boot.json, trace.otlp.json; `lab compare` works on it)")
    if export:
        info(f"Grafana: {observe.GRAFANA_URL}/d/lab-boot?var-build={build}&var-boot={last[0]['run']}")
    return run_id


def report(d, phases, trace_id, top=15):
    ms = lambda s: f"{s * 1e3:,.1f} ms" if s is not None else "?"
    print()
    print(table([[k, ms(phases.get(k))] for k in ("prekernel", "kernel", "userspace", "total")],
                ["phase", "time"]))
    print()
    print(table([[f"{s:8.3f}s", n] for n, s, _ in d["milestones"]], ["at", "kernel milestone"]))
    print()
    rows = [[name, f"{(end - start) * 1e3:,.1f} ms", n]
            for name, start, end, n in d["level_summary"]]
    print(table(rows, ["initcall level", "time", "initcalls"]))
    print()
    slow = sorted(d["initcalls"], key=lambda c: c["start"] - c["end"])[:top]
    print(table([[c["fn"], c["level"], f"{(c['end'] - c['start']) * 1e6:,.0f} us"] for c in slow],
                [f"slowest {top} initcalls", "level", "time"]))
    print()
    units = sorted(d["units"], key=lambda u: u["start"] - u["end"])[:top]
    print(table([[u["unit"], f"{(u['end'] - u['start']) * 1e3:,.1f} ms"] for u in units],
                [f"slowest {top} systemd units", "time"]))
